import {
  Body,
  Container,
  Column,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Row,
  Section,
  Text,
  Link,
} from "@react-email/components";
import * as React from "react";

interface ContactFormData {
  name: string;
  email: string;
  phone?: string;
  topic: string;
  message: string;
}

const TOPIC_EMOJI: Record<string, string> = {
  "General Inquiry": "💬",
  "Savings & Pricing": "💰",
  "Gift Wallet & Rewards": "🎁",
  "Technical Support": "🔧",
  Partnership: "🤝",
  Other: "📋",
};

export const ContactAdminEmail = ({
  name,
  email,
  phone,
  topic,
  message,
}: ContactFormData) => {
  const topicEmoji = TOPIC_EMOJI[topic] ?? "📋";
  const receivedAt = new Date().toLocaleString("en-CA", {
    timeZone: "America/Vancouver",
    dateStyle: "full",
    timeStyle: "short",
  });

  return (
    <Html lang="en">
      <Head />
      <Preview>
        New contact from {name} — {topic}
      </Preview>

      <Body style={body}>
        {/* ── Outer wrapper ── */}
        <Container style={outer}>

          {/* ── Header strip ── */}
          <Section style={header}>
            {/* Maple leaf wordmark */}
            <Row>
              <Column align="center">
                <Text style={brand}>🍁 Canadian Cart</Text>
                <Text style={brandSub}>Admin Notification</Text>
              </Column>
            </Row>
          </Section>

          {/* ── Hero badge ── */}
          <Section style={heroBadgeWrap}>
            <Text style={heroBadge}>New Contact Query</Text>
          </Section>

          {/* ── Card ── */}
          <Section style={card}>

            {/* Topic pill */}
            <Section style={{ paddingBottom: "20px" }}>
              <Text style={topicPill}>
                {topicEmoji}&nbsp;&nbsp;{topic}
              </Text>
            </Section>

            {/* Name / Email / Phone grid */}
            <Row style={fieldRow}>
              <Column style={fieldCol}>
                <Text style={fieldLabel}>Full Name</Text>
                <Text style={fieldValue}>{name}</Text>
              </Column>
              <Column style={fieldColRight}>
                <Text style={fieldLabel}>Email Address</Text>
                <Text style={fieldValue}>
                  <Link href={`mailto:${email}`} style={linkStyle}>
                    {email}
                  </Link>
                </Text>
              </Column>
            </Row>

            <Hr style={divider} />

            <Row style={fieldRow}>
              <Column style={fieldCol}>
                <Text style={fieldLabel}>Phone Number</Text>
                <Text style={fieldValue}>
                  {phone ? (
                    <Link href={`tel:${phone}`} style={linkStyle}>
                      {phone}
                    </Link>
                  ) : (
                    <span style={emptyVal}>Not provided</span>
                  )}
                </Text>
              </Column>
              <Column style={fieldColRight}>
                <Text style={fieldLabel}>Received At</Text>
                <Text style={fieldValue}>{receivedAt}</Text>
              </Column>
            </Row>

            <Hr style={divider} />

            {/* Message block */}
            <Section>
              <Text style={fieldLabel}>Message</Text>
              <Section style={messageBox}>
                <Text style={messageText}>{message}</Text>
              </Section>
            </Section>

          </Section>

          {/* ── CTA ── */}
          <Section style={ctaSection}>
            <Link href={`mailto:${email}?subject=Re: ${encodeURIComponent(topic)}`} style={ctaButton}>
              Reply to {name.split(" ")[0]}
            </Link>
          </Section>

          {/* ── Footer ── */}
          <Section style={footer}>
            <Text style={footerText}>
              This email was automatically generated by the Canadian Cart contact form.
              Do not reply directly to this email — use the button above to reach the customer.
            </Text>
            <Text style={footerMuted}>© {new Date().getFullYear()} Canadian Cart · Vancouver, BC</Text>
          </Section>

        </Container>
      </Body>
    </Html>
  );
};

export default ContactAdminEmail;

/* ── Styles ── */

const body: React.CSSProperties = {
  backgroundColor: "#f5f0e8",
  fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
  margin: 0,
  padding: "32px 0",
};

const outer: React.CSSProperties = {
  maxWidth: "600px",
  margin: "0 auto",
};

/* Header */
const header: React.CSSProperties = {
  backgroundColor: "#166534", // green-800
  borderRadius: "20px 20px 0 0",
  padding: "28px 40px 22px",
  textAlign: "center",
};

const brand: React.CSSProperties = {
  color: "#ffffff",
  fontSize: "22px",
  fontWeight: "800",
  letterSpacing: "-0.02em",
  margin: "0 0 2px",
};

const brandSub: React.CSSProperties = {
  color: "#bbf7d0", // green-200
  fontSize: "11px",
  fontWeight: "600",
  letterSpacing: "0.12em",
  textTransform: "uppercase",
  margin: 0,
};

/* Hero badge */
const heroBadgeWrap: React.CSSProperties = {
  backgroundColor: "#15803d", // green-700
  padding: "0 40px",
  textAlign: "center",
};

const heroBadge: React.CSSProperties = {
  display: "inline-block",
  backgroundColor: "#dcfce7", // green-100
  color: "#166534",           // green-800
  fontSize: "12px",
  fontWeight: "700",
  letterSpacing: "0.1em",
  textTransform: "uppercase",
  borderRadius: "999px",
  padding: "6px 18px",
  margin: "16px auto",
};

/* Card */
const card: React.CSSProperties = {
  backgroundColor: "#ffffff",
  padding: "36px 40px",
  borderRadius: "0 0 20px 20px",
  boxShadow: "0 4px 24px rgba(22, 101, 52, 0.08)",
};

/* Topic pill */
const topicPill: React.CSSProperties = {
  display: "inline-block",
  backgroundColor: "#f0fdf4", // green-50
  color: "#15803d",
  border: "1px solid #bbf7d0",
  borderRadius: "999px",
  fontSize: "13px",
  fontWeight: "700",
  padding: "6px 16px",
  margin: "0 0 4px",
};

/* Field rows */
const fieldRow: React.CSSProperties = {
  margin: "0 0 4px",
};

const fieldCol: React.CSSProperties = {
  width: "50%",
  paddingRight: "16px",
  verticalAlign: "top",
};

const fieldColRight: React.CSSProperties = {
  width: "50%",
  paddingLeft: "16px",
  verticalAlign: "top",
};

const fieldLabel: React.CSSProperties = {
  color: "#9ca3af", // gray-400
  fontSize: "10px",
  fontWeight: "700",
  letterSpacing: "0.1em",
  textTransform: "uppercase",
  margin: "0 0 4px",
};

const fieldValue: React.CSSProperties = {
  color: "#111827", // gray-900
  fontSize: "14px",
  fontWeight: "600",
  margin: "0 0 16px",
  lineHeight: "1.4",
};

const emptyVal: React.CSSProperties = {
  color: "#d1d5db",
  fontStyle: "italic",
  fontWeight: "400",
};

const linkStyle: React.CSSProperties = {
  color: "#15803d",
  textDecoration: "underline",
};

const divider: React.CSSProperties = {
  borderColor: "#f0fdf4",
  borderTopWidth: "1px",
  margin: "4px 0 20px",
};

/* Message box */
const messageBox: React.CSSProperties = {
  backgroundColor: "#fafaf8",
  border: "1px solid #e5e7eb",
  borderLeft: "3px solid #16a34a",
  borderRadius: "10px",
  padding: "16px 20px",
  marginTop: "8px",
};

const messageText: React.CSSProperties = {
  color: "#374151",
  fontSize: "14px",
  lineHeight: "1.7",
  margin: 0,
  whiteSpace: "pre-wrap",
};

/* CTA */
const ctaSection: React.CSSProperties = {
  textAlign: "center",
  padding: "28px 0 8px",
};

const ctaButton: React.CSSProperties = {
  display: "inline-block",
  backgroundColor: "#15803d",
  color: "#ffffff",
  fontSize: "14px",
  fontWeight: "700",
  borderRadius: "999px",
  padding: "14px 36px",
  textDecoration: "none",
  letterSpacing: "0.01em",
  boxShadow: "0 4px 14px rgba(21, 128, 61, 0.3)",
};

/* Footer */
const footer: React.CSSProperties = {
  textAlign: "center",
  padding: "16px 40px 8px",
};

const footerText: React.CSSProperties = {
  color: "#9ca3af",
  fontSize: "11px",
  lineHeight: "1.6",
  margin: "0 0 6px",
};

const footerMuted: React.CSSProperties = {
  color: "#d1d5db",
  fontSize: "10px",
  margin: 0,
};